# Dynamodb Tables
Resources:
  # Events Table
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: socless_events
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 200
        WriteCapacityUnits: 200

  # Execution Results Table
  ExecutionResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: socless_execution_results
        AttributeDefinitions:
          -
            AttributeName: execution_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: execution_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 60
          WriteCapacityUnits: 60


  # Message Responses Table
  MessageResponsesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: socless_message_responses
      AttributeDefinitions:
        -
          AttributeName: message_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: message_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50

  # Playbooks Table
  PlaybooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: socless_playbooks
      AttributeDefinitions:
        -
          AttributeName: StateMachine
          AttributeType: S
      KeySchema:
        -
          AttributeName: StateMachine
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lists Table
  CustomMappingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: socless_custom_mappings
      AttributeDefinitions:
        -
          AttributeName: key
          AttributeType: S
      KeySchema:
        -
          AttributeName: key
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  # Dedup Table
  DedupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: socless_dedup
      AttributeDefinitions:
        -
          AttributeName: dedup_hash
          AttributeType: S
      KeySchema:
        -
          AttributeName: dedup_hash
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50


# Resource outputs
Outputs:
  # Event Table name
  EventsTable:
    Description: "Socless Events Table"
    Value:
      Ref: EventsTable


  # Execution Results Table name
  ExecutionResultsTable:
    Description: "Socless Execution Results Table"
    Value:
      Ref: ExecutionResultsTable

  # Message Responses Table name
  MessageResponsesTable:
    Description: "Socless Message Responses Table"
    Value:
      Ref: MessageResponsesTable

  # Playbooks Table name
  PlaybooksTable:
    Description: "Socless Playbooks Table"
    Value:
      Ref: PlaybooksTable

  # Lists Table name
  CustomMappingsTable:
    Description: "Socless Custom Mappings Table"
    Value:
      Ref: CustomMappingsTable

  # Dedup Table name
  DedupTable:
    Description: "Socless Dedup Table"
    Value:
      Ref: DedupTable
