name: Deploy Docs

on:
  push:
    branches: 
      - master

jobs:
  deploy-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs-requirements.txt
    - name: deploy using mkdocs
      run: |
        mkdocs gh-deploy
